### ISSUE TITLE
getting absolute XPATH and CSS when using chrome for <a> (hyperlink web element)..please suggest steps again

### ISSUE THREAD

**Issue by KanikaSri** [tabhresh/Edureka_23July#3]
Steps to reproduce:
1. launch chrome browser and get Edureka home page.
2. Inspect top Categories hyperlink "Big data"
3. Copy-Xpath or Copy- Selector
Issue:
Getting Absolute path every time for XPAth and CSS
exp:
 XPATH: /html/body/div[2]/section/section[1]/div/section[3]/div/div/div/ul/li[2]/a
CSS:body > div.page-wrapper > section > section.row.top_home_img > div > section.row.easy_link_cat > div > div > div > ul > li:nth-child(2) > a
please guide what i missed
Note: Issue exist with Firefox also

**Comment by tabhresh** [comment]
Since it is a designing pattern issue. We will discuss about this after customized Xpath topic is covered

**Comment by KanikaSri** [comment]
please let me know solution for same as Advanced XPATH and all are done but still i m not able to understand

**Comment by tabhresh** [comment]
Solution to your problem
HTML view:-  <a href="/big-data-and-analytics">Big Data</a>
Coppied Xpath:-  /html/body/div[2]/section/section[1]/div/section[3]/div/div/div/ul/li[2]/a
Customized xpath:-  //li[2]/a[text() ='Big Data']
